### ISSUE TITLE
Unexpected error class=17 (MPI_ERR_INTERN: internal error), expected=6

### ISSUE THREAD

**Issue by jeffhammond** [pmodels/casper#22]
This test fails with Open-MPI on Linux.  Is the test overzealous or is Open-MPI RMA buggy w.r.t. error codes?
```
testing mpiexec=mpiexec -np 4 CSP_NG=0 win_errhan ...
CASPER Configuration:  
    RMA_ERR_CHECK    (enabled) 
    CSP_VERBOSE      = err||conf_g||
    CSP_NG           = 0
    CSP_ASYNC_CONFIG = on

Unexpected error class=17 (MPI_ERR_INTERN: internal error), expected=6
In win_errhan_fnc: error class does not match
Unexpected error class=17 (MPI_ERR_INTERN: internal error), expected=6
Return error class does not match
```
https://travis-ci.org/pmodels/casper/jobs/220763732
https://s3.amazonaws.com/archive.travis-ci.org/jobs/220763732/log.txt

**Comment by minsii** [comment]
It seems an OpenMPI issue. Because CSP_NG is 0, which means casper does nothing. I will confirm.

**Comment by minsii** [comment]
Confirmed that this is because OMPI does not return MPI_ERR_RANK error code if user uses invalid rank (e.g., win_lock(rank = -2)). Standard does not force implementation to return that code though. I think we just allow similar failure in tests `win_errhan` and `comm_errhan` with CSP_NG=0.

**Comment by jeffhammond** [comment]
I reported the bug and submitted a PR to fix it.

**Comment by jeffhammond** [comment]
Open-MPI merged my bugfix last year...
