### ISSUE TITLE
detect submodule issues in autogen.sh

### ISSUE THREAD

**Issue by jeffhammond** [pmodels/casper#30]
This was discussed over email on August 29, 2018 but I am creating an issue for tracking.

GitHub makes it really easy for users to clone without `--recursive` and thus not get the submodules.

`./autogen.sh` should detect the lack of submodules and provide a helpful error message rather failing as follows:

```
=== Applying patches ===
Applying patch to src/hwloc...
Applying: hwloc: separated visibility cflags for better control.
error: sha1 information is lacking or useless (config/hwloc.m4).
error: could not build fake ancestor
Patch failed at 0001 hwloc: separated visibility cflags for better control.
The copy of the patch that failed is found in: .git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
done

=== Running third-party initialization in src/hwloc ===
./autogen.sh: line 147: ./autogen.sh: No such file or directory
```

**Comment by nitinehpc** [comment]
Ha Ha, I am also seeing the same issue. 

$ ./autogen.sh
Checking for autoconf version...done
Checking for automake version...done
Checking for libtool version...done

Checking header file mpi.h at /apps/mpi/intel64/bin/../ ...done
Found /apps/mpi/intel64/include/mpi.h
Generating MPI wrappers... mpihstyle=_mpich
done

Checking header file mpio.h at / apps/mpi/intel64/bin/../ ...done
Found / apps/mpi/intel64/include/mpio.h
Generating MPI IO wrappers... mpihstyle=_mpich
done

Syncronizing confdb -> test/confdb... done

=== Applying patches ===
Applying patch to src/hwloc...
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
done

=== Running third-party initialization in src/hwloc ===
./autogen.sh: line 147: ./autogen.sh: No such file or directory

**Comment by jeffhammond** [comment]
The solution is to `git clone  --recursive`...

**Comment by devreal** [comment]
It appears that `http://git.mpich.org/` is not available anymore (timing out). Looks like openpa has moved to `https://github.com/pmodels/openpa`...

**Comment by jeffhammond** [comment]
Yeah, I think the migration of OpenPA is recent.  I'm sure one of the Argonne folks will fix this soon enough.

**Comment by jeffhammond** [comment]
The OpenPA repo location issue was fixed in https://github.com/pmodels/casper/pull/34/commits/242c7cafdad32ab011b4a00121d1f963024c219b and merged just now (https://github.com/pmodels/casper/pull/34).

**Comment by jeffhammond** [comment]
Attempting a fix in https://github.com/pmodels/casper/pull/38...
