### ISSUE TITLE
Cannot download casper source code from official website.

### ISSUE THREAD

**Issue by rangsimanketkaew** [pmodels/casper#33]
I tried to download the tarball of casper source code on https://www.mcs.anl.gov/project/casper/downloads/, but it seems that the file is no longer existing on the server.

Have you found this issue and where can I download the casper?

P.S. The download link url is https://www.mcs.anl.gov/~minsi/release/casper-1.0b2.tar.gz.

Rangsiman

**Comment by jeffhammond** [comment]
Please try https://github.com/pmodels/casper/releases instead.

**Comment by rangsimanketkaew** [comment]
Successfully installed casper. Thanks a lot.
